//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 10/7/2009 4:17:14 PM
namespace Taskr.Silverlight.TaskRDataService
{
    
    /// <summary>
    /// There are no comments for TaskrDataContext in the schema.
    /// </summary>
    public partial class TaskrDataContext : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new TaskrDataContext object.
        /// </summary>
        public TaskrDataContext(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("Apprenda.Taskr", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("Taskr.Silverlight.TaskRDataService", typeName.Substring(14)), true);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("Taskr.Silverlight.TaskRDataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("Apprenda.Taskr.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Tag> Tags
        {
            get
            {
                if ((this._Tags == null))
                {
                    this._Tags = base.CreateQuery<Tag>("Tags");
                }
                return this._Tags;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Tag> _Tags;
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        public global::System.Data.Services.Client.DataServiceQuery<Task> Tasks
        {
            get
            {
                if ((this._Tasks == null))
                {
                    this._Tasks = base.CreateQuery<Task>("Tasks");
                }
                return this._Tasks;
            }
        }
        private global::System.Data.Services.Client.DataServiceQuery<Task> _Tasks;
        /// <summary>
        /// There are no comments for Tags in the schema.
        /// </summary>
        public void AddToTags(Tag tag)
        {
            base.AddObject("Tags", tag);
        }
        /// <summary>
        /// There are no comments for Tasks in the schema.
        /// </summary>
        public void AddToTasks(Task task)
        {
            base.AddObject("Tasks", task);
        }
    }
    /// <summary>
    /// There are no comments for Apprenda.Taskr.Tag in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Tag
    {
        /// <summary>
        /// Create a new Tag object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        public static Tag CreateTag(global::System.Guid ID)
        {
            Tag tag = new Tag();
            tag.Id = ID;
            return tag;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Label in the schema.
        /// </summary>
        public string Label
        {
            get
            {
                return this._Label;
            }
            set
            {
                this.OnLabelChanging(value);
                this._Label = value;
                this.OnLabelChanged();
            }
        }
        private string _Label;
        partial void OnLabelChanging(string value);
        partial void OnLabelChanged();
    }
    /// <summary>
    /// There are no comments for Apprenda.Taskr.Task in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::System.Data.Services.Common.DataServiceKeyAttribute("Id")]
    public partial class Task
    {
        /// <summary>
        /// Create a new Task object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="dueDate">Initial value of DueDate.</param>
        public static Task CreateTask(global::System.Guid ID, global::System.DateTime dueDate)
        {
            Task task = new Task();
            task.Id = ID;
            task.DueDate = dueDate;
            return task;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        public global::System.Guid Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Subject in the schema.
        /// </summary>
        public string Subject
        {
            get
            {
                return this._Subject;
            }
            set
            {
                this.OnSubjectChanging(value);
                this._Subject = value;
                this.OnSubjectChanged();
            }
        }
        private string _Subject;
        partial void OnSubjectChanging(string value);
        partial void OnSubjectChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
            }
        }
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property DueDate in the schema.
        /// </summary>
        public global::System.DateTime DueDate
        {
            get
            {
                return this._DueDate;
            }
            set
            {
                this.OnDueDateChanging(value);
                this._DueDate = value;
                this.OnDueDateChanged();
            }
        }
        private global::System.DateTime _DueDate;
        partial void OnDueDateChanging(global::System.DateTime value);
        partial void OnDueDateChanged();
        /// <summary>
        /// There are no comments for Property RawPriority in the schema.
        /// </summary>
        public global::System.Nullable<int> RawPriority
        {
            get
            {
                return this._RawPriority;
            }
            set
            {
                this.OnRawPriorityChanging(value);
                this._RawPriority = value;
                this.OnRawPriorityChanged();
            }
        }
        private global::System.Nullable<int> _RawPriority;
        partial void OnRawPriorityChanging(global::System.Nullable<int> value);
        partial void OnRawPriorityChanged();
    }
}
